//! Generates the TypeScript for `app/src/ipc/proto.gen.ts` from the C1 and C3 types.
//!
//! `scripts/gen.ts` runs this test with `PLY_GEN_OUT=<file>`, formats the output with Biome and writes (or, with
//! `--check`, compares) `app/src/ipc/proto.gen.ts`. Without the variable the test still checks that every type
//! the exported ones refer to is exported too.

#![allow(clippy::unwrap_used, clippy::expect_used)]

use std::any::TypeId;
use std::collections::BTreeSet;
use std::path::PathBuf;

use ply_proto::control::{
    Answer, Call, ClientMsg, DaemonShutdownParams, DaemonStopping, Empty, ErrorBody, ErrorCode,
    Event, HANDSHAKE_ID, Hello, LayoutSaveParams, MAX_LINE_BYTES, METHODS, PaneAnswerParams,
    PaneCloseParams, PaneCreateParams, PaneExit, PaneMeta, PaneProgress, PaneRef, PaneRemoved,
    PaneStatusChanged, Request, Response, ServerMsg, SessionListParams, SettingsSetParams,
    ThemeSetParams, Welcome, WorkspaceOpenParams, WorkspaceRef, WorktreeOption,
};
use ply_proto::hook::HookEnvelope;
use ply_proto::pane::{
    AccentName, AgentCli, Cli, Layout, OptionAsMeta, Pane, PaneStatus, Progress, Rgb, Session,
    Settings, Tab, TerminalTheme, Workspace,
};
use ply_proto::{C2_VERSION, HOOK_VERSION, PROTOCOL_VERSION};
use ts_rs::{Config, TS};

/// Types whose Rust side overrides the TypeScript shape (`#[ts(type = ..)]`): name, TypeScript type, doc.
const ALIASES: [(&str, &str, &str); 1] =
    [("Rgb", "string", "An opaque sRGB colour, `\"#RRGGBB\"`.")];

struct Decl {
    name: String,
    text: String,
    deps: Vec<(TypeId, String)>,
}

fn decl<T: TS + 'static + ?Sized>(cfg: &Config) -> Decl {
    let docs = T::docs().unwrap_or_default();
    Decl {
        name: T::ident(cfg),
        text: format!("{docs}export {}", T::decl(cfg)),
        deps: T::dependencies(cfg)
            .into_iter()
            .map(|d| (d.type_id, d.ts_name))
            .collect(),
    }
}

fn generate() -> String {
    let cfg = Config::new().with_large_int("number");
    let decls = vec![
        decl::<serde_json::Value>(&cfg),
        decl::<Cli>(&cfg),
        decl::<AgentCli>(&cfg),
        decl::<PaneStatus>(&cfg),
        decl::<Progress>(&cfg),
        decl::<Pane>(&cfg),
        decl::<Workspace>(&cfg),
        decl::<Tab>(&cfg),
        decl::<Layout>(&cfg),
        decl::<Session>(&cfg),
        decl::<TerminalTheme>(&cfg),
        decl::<AccentName>(&cfg),
        decl::<OptionAsMeta>(&cfg),
        decl::<Settings>(&cfg),
        decl::<ClientMsg>(&cfg),
        decl::<ServerMsg>(&cfg),
        decl::<Hello>(&cfg),
        decl::<Welcome>(&cfg),
        decl::<Request>(&cfg),
        decl::<Call>(&cfg),
        decl::<Response>(&cfg),
        decl::<ErrorCode>(&cfg),
        decl::<ErrorBody>(&cfg),
        decl::<Empty>(&cfg),
        decl::<WorkspaceOpenParams>(&cfg),
        decl::<WorkspaceRef>(&cfg),
        decl::<PaneRef>(&cfg),
        decl::<WorktreeOption>(&cfg),
        decl::<PaneCreateParams>(&cfg),
        decl::<PaneCloseParams>(&cfg),
        decl::<Answer>(&cfg),
        decl::<PaneAnswerParams>(&cfg),
        decl::<SessionListParams>(&cfg),
        decl::<ThemeSetParams>(&cfg),
        decl::<LayoutSaveParams>(&cfg),
        decl::<SettingsSetParams>(&cfg),
        decl::<DaemonShutdownParams>(&cfg),
        decl::<Event>(&cfg),
        decl::<PaneRemoved>(&cfg),
        decl::<PaneStatusChanged>(&cfg),
        decl::<PaneProgress>(&cfg),
        decl::<PaneMeta>(&cfg),
        decl::<PaneExit>(&cfg),
        decl::<DaemonStopping>(&cfg),
        decl::<HookEnvelope>(&cfg),
    ];

    let mut declared: BTreeSet<&str> = decls.iter().map(|d| d.name.as_str()).collect();
    for (name, _, _) in ALIASES {
        declared.insert(name);
    }
    for d in &decls {
        for (_, dep) in &d.deps {
            assert!(
                declared.contains(dep.as_str()),
                "{} depends on {dep}, which is not exported",
                d.name
            );
        }
    }

    let mut out = String::from(
        "// generated by `bun run gen` from crates/proto (ts-rs) — do not edit\n\
         // Integers are TypeScript numbers: ids and timestamps stay below 2^53.\n\n",
    );
    for (name, ty, doc) in ALIASES {
        out.push_str(&format!("/** {doc} */\nexport type {name} = {ty};\n\n"));
    }
    for d in &decls {
        out.push_str(&d.text);
        out.push_str("\n\n");
    }
    out.push_str(
        "/** C1 methods: the params each takes and the `r` value of its successful response. */\n",
    );
    out.push_str("export type Methods = {\n");
    for m in METHODS {
        out.push_str(&format!(
            "  \"{}\": {{ params: {}; result: {} }};\n",
            m.name, m.params, m.result
        ));
    }
    out.push_str("};\n\n");
    out.push_str("/** A C1 method name. */\nexport type Method = keyof Methods;\n\n");
    let consts = [
        (
            "PROTOCOL_VERSION",
            "C1 protocol version sent in `hello.v`.",
            u64::from(PROTOCOL_VERSION),
        ),
        (
            "C2_VERSION",
            "C2 version sent in ATTACH.",
            u64::from(C2_VERSION),
        ),
        (
            "HOOK_VERSION",
            "C3 envelope version.",
            u64::from(HOOK_VERSION),
        ),
        (
            "MAX_LINE_BYTES",
            "Longest C1 line in bytes, newline included.",
            MAX_LINE_BYTES as u64,
        ),
        (
            "HANDSHAKE_ID",
            "Response id plyd uses to reject a `hello`; requests start at 1.",
            HANDSHAKE_ID,
        ),
    ];
    for (name, doc, value) in consts {
        out.push_str(&format!("/** {doc} */\nexport const {name} = {value};\n\n"));
    }
    out.truncate(out.trim_end().len());
    out.push('\n');
    out
}

#[test]
fn export_bindings() {
    let generated = generate();
    if let Some(out) = std::env::var_os("PLY_GEN_OUT") {
        std::fs::write(PathBuf::from(out), generated).expect("write the generated bindings");
    }
}

fn black_theme() -> TerminalTheme {
    let c = Rgb { r: 0, g: 0, b: 0 };
    TerminalTheme {
        ansi: [c; 16],
        fg: c,
        bg: c,
        cursor: c,
        cursor_text: c,
        selection_bg: c,
        selection_fg: c,
    }
}

#[test]
fn method_table_matches_call() {
    let names: Vec<&str> = METHODS.iter().map(|m| m.name).collect();
    let calls = [
        Call::WorkspaceList(Empty {}),
        Call::WorkspaceOpen(WorkspaceOpenParams {
            path: String::new(),
        }),
        Call::PaneList(WorkspaceRef { workspace_id: 1 }),
        Call::PaneCreate(PaneCreateParams {
            workspace_id: 1,
            tab_id: None,
            cli: Cli::Shell,
            cwd: String::new(),
            worktree: None,
            prompt: None,
        }),
        Call::PaneClose(PaneCloseParams {
            pane_id: 1,
            kill: false,
        }),
        Call::PaneAnswer(PaneAnswerParams {
            pane_id: 1,
            answer: Answer::No,
        }),
        Call::PaneResume(PaneRef { pane_id: 1 }),
        Call::SessionList(SessionListParams {
            workspace_id: 1,
            include_closed: true,
        }),
        Call::ThemeSet(ThemeSetParams {
            palette: black_theme(),
        }),
        Call::LayoutGet(WorkspaceRef { workspace_id: 1 }),
        Call::LayoutSave(LayoutSaveParams {
            workspace_id: 1,
            layout: Layout {
                tabs: vec![],
                active_tab_id: None,
            },
        }),
        Call::SettingsGet(Empty {}),
        Call::SettingsSet(SettingsSetParams {
            settings: Settings::default(),
        }),
        Call::DaemonShutdown(DaemonShutdownParams { kill_panes: false }),
    ];
    let from_calls: Vec<&str> = calls.iter().map(Call::method).collect();
    assert_eq!(names, from_calls);
    for call in &calls {
        let v = serde_json::to_value(call).unwrap();
        assert_eq!(v["m"], call.method());
    }
    let _ = Request {
        id: 1,
        call: Call::SettingsGet(Empty {}),
    };
    let _ = Response::err(1, ErrorCode::Internal, "x");
}
