// generated by `bun run gen` from crates/proto (ts-rs) — do not edit
// Integers are TypeScript numbers: ids and timestamps stay below 2^53.

/** An opaque sRGB colour, `"#RRGGBB"`. */
export type Rgb = string;

/** A `pane.answer` choice, written to the pty as that digit. */
export type Choice = 1 | 2 | 3;

export type JsonValue =
  | number
  | string
  | boolean
  | Array<JsonValue>
  | { [key in string]: JsonValue }
  | null;

/**
 * The program a pane runs (schema v1 `panes.cli`).
 */
export type Cli = 'claude' | 'codex' | 'shell';

/**
 * The CLIs that send C3 hook and notify payloads; a shell pane has no hooks.
 */
export type AgentCli = 'claude' | 'codex';

/**
 * Pane state per the spec 6.3 machine, a plain string on the wire; for `Exited` the code travels in `exit_code`.
 */
export type PaneStatus =
  | 'starting'
  | 'idle'
  | 'running'
  | 'waiting_permission'
  | 'waiting_input'
  | 'exited'
  | 'lost';

/**
 * Plan progress reported by the agent (spec 6.4): `done <= total`; `current` is the in-progress item's text.
 */
export type Progress = {
  /**
   * Completed items.
   */
  done: number;
  /**
   * All items.
   */
  total: number;
  /**
   * Text of the item in progress, if any.
   */
  current?: string;
};

/**
 * A live or finished pane as plyd tracks it; `id` is the C2 `pane_id` the terminal view attaches with.
 */
export type Pane = {
  /**
   * Pane id, equal to the C2 ATTACH `pane_id`.
   */
  id: number;
  /**
   * Workspace the pane belongs to.
   */
  workspace_id: number;
  /**
   * Tab the pane sits in.
   */
  tab_id: number;
  /**
   * 0-based place in its tab: 0 is the main pane, 1.. the stack from top to bottom.
   */
  position: number;
  /**
   * Program the pane runs.
   */
  cli: Cli;
  /**
   * Working directory as last reported (OSC 7 or the CLI's hook `cwd`), absolute.
   */
  cwd: string;
  /**
   * Title shown in the pane header (the terminal title when set, else the CLI name).
   */
  title: string;
  /**
   * Current state.
   */
  status: PaneStatus;
  /**
   * One line on the current state, e.g. the tool a permission prompt is for.
   */
  detail?: string;
  /**
   * Plan progress; absent when the agent reports no plan.
   */
  progress?: Progress;
  /**
   * Model name as the session reports it; ply never chooses it (spec 6.5).
   */
  model_seen?: string;
  /**
   * Worktree name the CLI reports for the pane's cwd; display and session record only (INV-7).
   */
  worktree_seen?: string;
  /**
   * Git branch of `cwd` (display only, never stored).
   */
  branch?: string;
  /**
   * The CLI's own session id (Claude `session_id`, Codex thread id), used to resume.
   */
  session_ref?: string;
  /**
   * Exit code, present exactly when `status` is `exited`; a signal death is reported as 128 + signal.
   */
  exit_code?: number;
  /**
   * When the pane was created.
   */
  created_at: number;
  /**
   * When the pane was closed; absent while it is open.
   */
  closed_at?: number;
  /**
   * Last pty output or hook event.
   */
  last_activity_at?: number;
};

/**
 * A directory ply opened; one default workspace (the home directory) exists after first run.
 */
export type Workspace = {
  /**
   * Workspace id.
   */
  id: number;
  /**
   * Absolute path, unique across workspaces.
   */
  path: string;
  /**
   * Display name.
   */
  name: string;
  /**
   * When it was last opened.
   */
  opened_at: number;
};

/**
 * One tab of a workspace with its pane order, focus and zoom.
 */
export type Tab = {
  /**
   * Tab id.
   */
  id: number;
  /**
   * Display name (the basename of its first pane's directory unless renamed).
   */
  name: string;
  /**
   * 0-based order in the tab bar.
   */
  position: number;
  /**
   * Panes in position order: the first is the main pane.
   */
  pane_ids: Array<number>;
  /**
   * Pane that has focus in this tab.
   */
  focus_pane_id?: number;
  /**
   * Whether the focused pane fills the tab.
   */
  zoomed: boolean;
};

/**
 * The tab arrangement of one workspace, as `layout.get` returns it and `layout.save` stores it.
 */
export type Layout = {
  /**
   * Tabs in any order; `Tab::position` orders them.
   */
  tabs: Array<Tab>;
  /**
   * Tab shown on open.
   */
  active_tab_id?: number;
};

/**
 * The stored record of a pane, kept after it closes (F3); `session.list` returns these.
 */
export type Session = {
  /**
   * Id of the pane that ran the session.
   */
  pane_id: number;
  /**
   * Workspace of that pane.
   */
  workspace_id: number;
  /**
   * Program it ran.
   */
  cli: Cli;
  /**
   * Its last working directory.
   */
  cwd: string;
  /**
   * Its last title.
   */
  title: string;
  /**
   * Its last state.
   */
  status: PaneStatus;
  /**
   * The CLI's session id, if one was reported.
   */
  session_ref?: string;
  /**
   * Model the session reported.
   */
  model_seen?: string;
  /**
   * Worktree the CLI reported.
   */
  worktree_seen?: string;
  /**
   * Exit code once exited.
   */
  exit_code?: number;
  /**
   * Start time.
   */
  created_at: number;
  /**
   * Close time.
   */
  closed_at?: number;
  /**
   * Last activity.
   */
  last_activity_at?: number;
};

/**
 * The terminal palette (`theme.set`, spec R-R4); camelCase keys to match the terminal view's `theme` prop.
 */
export type TerminalTheme = {
  /**
   * ANSI colours 0–15; exactly 16 entries or the message is rejected (a 16-tuple in TypeScript).
   */
  ansi: [
    string,
    string,
    string,
    string,
    string,
    string,
    string,
    string,
    string,
    string,
    string,
    string,
    string,
    string,
    string,
    string,
  ];
  /**
   * Default foreground (answers OSC 10).
   */
  fg: Rgb;
  /**
   * Default background (answers OSC 11).
   */
  bg: Rgb;
  /**
   * Cursor colour (answers OSC 12).
   */
  cursor: Rgb;
  /**
   * Text under a block cursor.
   */
  cursorText: Rgb;
  /**
   * Selection fill, already blended over `bg`.
   */
  selectionBg: Rgb;
  /**
   * Text inside the selection.
   */
  selectionFg: Rgb;
};

/**
 * Accent colour choice; the names match `accentAlternatives` in `app/src/theme/tokens.ts`.
 */
export type AccentName = 'blue' | 'mint' | 'violet' | 'sand';

/**
 * Which ⌥ key acts as Meta (spec K5); `off` keeps ⌥ for typing layout characters.
 */
export type OptionAsMeta = 'off' | 'left' | 'right' | 'both';

/**
 * User settings (`settings.get` / `settings.set`, ADR-0009); every field is required on the wire.
 */
export type Settings = {
  /**
   * Accent colour of the chrome and the terminal cursor.
   */
  accent: AccentName;
  /**
   * ⌥-as-Meta per side.
   */
  option_as_meta: OptionAsMeta;
  /**
   * Hold a prevent-idle-sleep assertion while any pane is running.
   */
  keep_awake_while_running: boolean;
  /**
   * Pass `"theme":"dark-ansi"` to Claude Code so it uses ply's palette.
   */
  use_ply_colours_in_claude: boolean;
  /**
   * Enable Codex's plan tool per invocation (`-c tools.update_plan.enabled=true`, Ruling R26).
   */
  codex_plan_tool: boolean;
  /**
   * Scrollback lines kept per pane in plyd.
   */
  scrollback_lines: number;
  /**
   * Font size in points for chrome and terminals.
   */
  font_size: number;
};

/**
 * Messages from the app to plyd, tagged by `"t"`.
 */
export type ClientMsg = ({ t: 'hello' } & Hello) | ({ t: 'req' } & Request);

/**
 * Messages from plyd to the app, tagged by `"t"`.
 */
export type ServerMsg =
  | ({ t: 'welcome' } & Welcome)
  | ({ t: 'res' } & Response)
  | ({ t: 'evt' } & Event);

/**
 * Handshake from the app; `v` must equal [`crate::PROTOCOL_VERSION`].
 */
export type Hello = {
  /**
   * Protocol version the client speaks.
   */
  v: number;
  /**
   * Client name, `"ply-app"` for the app.
   */
  client: string;
  /**
   * Client build version (semver).
   */
  app_version: string;
};

/**
 * Handshake answer from plyd.
 */
export type Welcome = {
  /**
   * Protocol version plyd speaks.
   */
  v: number;
  /**
   * plyd build version (semver).
   */
  daemon_version: string;
};

/**
 * A method call: `{"t":"req","id":…,"m":"<method>","p":{…}}`; `p` is required, `{}` for methods without params.
 */
export type Request = {
  /**
   * Caller-chosen id, echoed by the response; unique per connection, starting at 1.
   */
  id: number;
} & (
  | { m: 'workspace.list'; p: Empty }
  | { m: 'workspace.open'; p: WorkspaceOpenParams }
  | { m: 'pane.list'; p: WorkspaceRef }
  | { m: 'pane.create'; p: PaneCreateParams }
  | { m: 'pane.close'; p: PaneCloseParams }
  | { m: 'pane.answer'; p: PaneAnswerParams }
  | { m: 'pane.resume'; p: PaneRef }
  | { m: 'session.list'; p: SessionListParams }
  | { m: 'theme.set'; p: ThemeSetParams }
  | { m: 'layout.get'; p: WorkspaceRef }
  | { m: 'layout.save'; p: LayoutSaveParams }
  | { m: 'settings.get'; p: Empty }
  | { m: 'settings.set'; p: SettingsSetParams }
  | { m: 'daemon.shutdown'; p: DaemonShutdownParams }
);

/**
 * Every C1 method with its params, tagged `"m"` with params in `"p"`; [`METHODS`] gives each result type.
 */
export type Call =
  | { m: 'workspace.list'; p: Empty }
  | { m: 'workspace.open'; p: WorkspaceOpenParams }
  | { m: 'pane.list'; p: WorkspaceRef }
  | { m: 'pane.create'; p: PaneCreateParams }
  | { m: 'pane.close'; p: PaneCloseParams }
  | { m: 'pane.answer'; p: PaneAnswerParams }
  | { m: 'pane.resume'; p: PaneRef }
  | { m: 'session.list'; p: SessionListParams }
  | { m: 'theme.set'; p: ThemeSetParams }
  | { m: 'layout.get'; p: WorkspaceRef }
  | { m: 'layout.save'; p: LayoutSaveParams }
  | { m: 'settings.get'; p: Empty }
  | { m: 'settings.set'; p: SettingsSetParams }
  | { m: 'daemon.shutdown'; p: DaemonShutdownParams };

/**
 * The answer to a request: `{"t":"res","id","ok":true,"r":…}` or `{"t":"res","id","ok":false,"err":{…}}`.
 */
export type Response =
  | { id: number; ok: true; r: JsonValue }
  | { id: number; ok: false; err: ErrorBody };

/**
 * Closed set of C1 error codes (snake_case on the wire); clients match on these, never on `msg`.
 */
export type ErrorCode =
  | 'cli_not_found'
  | 'cli_too_old'
  | 'bad_request'
  | 'unknown_method'
  | 'version_mismatch'
  | 'not_found'
  | 'pane_alive'
  | 'invalid_state'
  | 'spawn_failed'
  | 'shutting_down'
  | 'internal';

/**
 * The error of a failed request.
 */
export type ErrorBody = {
  /**
   * Machine-readable code.
   */
  code: ErrorCode;
  /**
   * Human-readable message, shown to the user as is.
   */
  msg: string;
};

/**
 * Params of methods that take none: the empty object `{}`; also the result of methods that return nothing.
 */
export type Empty = Record<symbol, never>;

/**
 * `workspace.open` params.
 */
export type WorkspaceOpenParams = {
  /**
   * Absolute directory path; opening a known path returns the existing workspace.
   */
  path: string;
};

/**
 * Params naming one workspace (`pane.list`, `layout.get`).
 */
export type WorkspaceRef = {
  /**
   * Workspace id.
   */
  workspace_id: number;
};

/**
 * Params naming one pane (`pane.resume`).
 */
export type PaneRef = {
  /**
   * Pane id.
   */
  pane_id: number;
};

/**
 * The worktree option of `pane.create`, passed through to `claude --worktree <name>` (INV-7).
 */
export type WorktreeOption = {
  /**
   * Worktree name as Claude Code expects it.
   */
  name: string;
};

/**
 * `pane.create` params; without `tab_id` the pane opens a new tab, and `worktree` is valid for Claude only.
 */
export type PaneCreateParams = {
  /**
   * Workspace to create the pane in.
   */
  workspace_id: number;
  /**
   * Existing tab to add the pane to.
   */
  tab_id?: number;
  /**
   * Program to run.
   */
  cli: Cli;
  /**
   * Absolute working directory.
   */
  cwd: string;
  /**
   * Claude Code worktree to start in; `bad_request` for other CLIs.
   */
  worktree?: WorktreeOption;
  /**
   * First prompt, passed as the CLI's prompt argument.
   */
  prompt?: string;
};

/**
 * `pane.close` params: `kill: false` on a live pane fails with `pane_alive`; `kill: true` sends SIGHUP, then SIGKILL after 2 s.
 */
export type PaneCloseParams = {
  /**
   * Pane to close.
   */
  pane_id: number;
  /**
   * Stop a live process first.
   */
  kill: boolean;
};

/**
 * `pane.answer` params.
 */
export type PaneAnswerParams = {
  /**
   * Pane showing the CLI's dialog.
   */
  pane_id: number;
  /**
   * Option to pick.
   */
  choice: Choice;
};

/**
 * `session.list` params.
 */
export type SessionListParams = {
  /**
   * Workspace whose sessions to list.
   */
  workspace_id: number;
  /**
   * Include panes that were closed.
   */
  include_closed: boolean;
};

/**
 * `theme.set` params.
 */
export type ThemeSetParams = {
  /**
   * Palette every pane's terminal answers colour queries from; stored across restarts.
   */
  palette: TerminalTheme;
};

/**
 * `layout.save` params.
 */
export type LayoutSaveParams = {
  /**
   * Workspace the layout belongs to.
   */
  workspace_id: number;
  /**
   * The layout to store, replacing the previous one.
   */
  layout: Layout;
};

/**
 * `settings.set` params.
 */
export type SettingsSetParams = {
  /**
   * The complete settings, replacing the stored ones.
   */
  settings: Settings;
};

/**
 * `daemon.shutdown` params.
 */
export type DaemonShutdownParams = {
  /**
   * Stop every pane's process before exiting ("Quit ply and stop sessions").
   */
  kill_panes: boolean;
};

/**
 * Daemon events, tagged `"e"` with the payload in `"p"`; broadcast to every connected client.
 */
export type Event =
  | { e: 'pane.added'; p: Pane }
  | { e: 'pane.removed'; p: PaneRemoved }
  | { e: 'pane.status'; p: PaneStatusChanged }
  | { e: 'pane.progress'; p: PaneProgress }
  | { e: 'pane.meta'; p: PaneMeta }
  | { e: 'pane.exit'; p: PaneExit }
  | { e: 'daemon.stopping'; p: DaemonStopping };

/**
 * `pane.removed` payload.
 */
export type PaneRemoved = {
  /**
   * The pane that was closed.
   */
  pane_id: number;
};

/**
 * `pane.status` payload; `exit_code` is present exactly when `status` is `exited`.
 */
export type PaneStatusChanged = {
  /**
   * The pane.
   */
  pane_id: number;
  /**
   * Its new state.
   */
  status: PaneStatus;
  /**
   * One line on the state, e.g. the tool awaiting permission.
   */
  detail?: string;
  /**
   * Exit code for `exited`.
   */
  exit_code?: number;
  /**
   * When plyd observed the signal behind the change.
   */
  at: number;
};

/**
 * `pane.progress` payload, sent at most 4 times a second per pane; no `progress` hides the bar.
 */
export type PaneProgress = {
  /**
   * The pane.
   */
  pane_id: number;
  /**
   * The agent's plan progress.
   */
  progress?: Progress;
};

/**
 * `pane.meta` payload (Ruling R4): what the session reports about itself; absent fields are unknown.
 */
export type PaneMeta = {
  /**
   * The pane.
   */
  pane_id: number;
  /**
   * Model as the session reports it.
   */
  model?: string;
  /**
   * Worktree name the CLI reports.
   */
  worktree?: string;
  /**
   * Current working directory, absolute.
   */
  cwd: string;
  /**
   * Git branch of `cwd`.
   */
  branch?: string;
};

/**
 * `pane.exit` payload.
 */
export type PaneExit = {
  /**
   * The pane.
   */
  pane_id: number;
  /**
   * Exit code; a signal death is 128 + signal.
   */
  code: number;
  /**
   * When the process ended.
   */
  at: number;
};

/**
 * `daemon.stopping` payload, sent to every client before plyd exits.
 */
export type DaemonStopping = {
  /**
   * Whether the panes' processes are being stopped too.
   */
  kill_panes: boolean;
};

/**
 * `{"v":1,"pane_id":2,"cli":"claude","event":"Notification","payload":{…}}`; `event` is absent for Codex notify.
 */
export type HookEnvelope = {
  /**
   * Envelope version, [`crate::HOOK_VERSION`].
   */
  v: number;
  /**
   * Pane that ran the hook, from `PLY_PANE_ID`.
   */
  pane_id: number;
  /**
   * CLI that sent it (`ply-hook`'s first argument).
   */
  cli: AgentCli;
  /**
   * Hook event name (`ply-hook`'s second argument), e.g. `"PermissionRequest"`.
   */
  event?: string;
  /**
   * The CLI's payload exactly as received; never interpreted by `ply-hook`.
   */
  payload: JsonValue;
};

/** C1 methods: the params each takes and the `r` value of its successful response. */
export type Methods = {
  'workspace.list': { params: Empty; result: Array<Workspace> };
  'workspace.open': { params: WorkspaceOpenParams; result: Workspace };
  'pane.list': { params: WorkspaceRef; result: Array<Pane> };
  'pane.create': { params: PaneCreateParams; result: Pane };
  'pane.close': { params: PaneCloseParams; result: Empty };
  'pane.answer': { params: PaneAnswerParams; result: Empty };
  'pane.resume': { params: PaneRef; result: Pane };
  'session.list': { params: SessionListParams; result: Array<Session> };
  'theme.set': { params: ThemeSetParams; result: Empty };
  'layout.get': { params: WorkspaceRef; result: Layout };
  'layout.save': { params: LayoutSaveParams; result: Empty };
  'settings.get': { params: Empty; result: Settings };
  'settings.set': { params: SettingsSetParams; result: Empty };
  'daemon.shutdown': { params: DaemonShutdownParams; result: Empty };
};

/** A C1 method name. */
export type Method = keyof Methods;

/** C1 protocol version sent in `hello.v`. */
export const PROTOCOL_VERSION = 1;

/** C2 version sent in ATTACH. */
export const C2_VERSION = 1;

/** C3 envelope version. */
export const HOOK_VERSION = 1;

/** Longest C1 line in bytes, newline included. */
export const MAX_LINE_BYTES = 1048576;

/** Response id plyd uses to reject a `hello`; requests start at 1. */
export const HANDSHAKE_ID = 0;
